package com.viosng.confsql.semantic.model.thrift; /**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import org.apache.thrift.TEnum;

public enum ThriftQueryType implements TEnum {
  PRIMARY(1),
  FILTER(2),
  FUSION(3),
  JOIN(4),
  AGGREGATION(5),
  NEST(6),
  UNNEST(7),
  GROUP_JOIN(8);

  private final int value;

  private ThriftQueryType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftQueryType findByValue(int value) { 
    switch (value) {
      case 1:
        return PRIMARY;
      case 2:
        return FILTER;
      case 3:
        return FUSION;
      case 4:
        return JOIN;
      case 5:
        return AGGREGATION;
      case 6:
        return NEST;
      case 7:
        return UNNEST;
      case 8:
        return GROUP_JOIN;
      default:
        return null;
    }
  }
}
